openapi: 3.0.3
info:
  title: Blog
  description: Blog
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /v1/articles:
    get:
      summary: Get all articles
      tags:
        - Articles
      operationId: getArticles
      responses:
        200:
          description: List of articles
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Articles"
    post:
      summary: create an article
      tags:
        - Articles
      operationId: createArticle
      requestBody:
        $ref: "#/components/schemas/Article"
      responses:
        201:
          description: A new article
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
  /v1/articles/{id}:
    put:
      summary: update an article
      tags:
        - Articles
      operationId: updateArticle
      requestBody:
        $ref: "#/components/schemas/Article"
      responses:
        200:
          description: A specific article
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
  /v1/users:
    get:
      summary: Get all users
      tags:
        - Users
      operationId: getUsers
      responses:
        200:
          description: List of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
    post:
      summary: create a user
      tags:
        - Users
      operationId: createUser
      requestBody:
        $ref: "#/components/schemas/User"
      responses:
        201:
          description: A new user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: string
          format: uuid
        content:
          type: string
    Articles:
      type: array
      items:
        $ref: "#/components/schemas/Article"
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"