version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: | 
            mvn test
            curl https://deepsource.io/cli | sh
            ./bin/deepsource report --analyzer test-coverage --key javascript --value-file target/site/jacoco/jacocoTestReport.xml
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r target/site/jacoco/jacocoTestReport.xml

workflows:
  test-workflow:
    jobs:
      - test